on: [push]

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run the action
        id: hello
        uses: ./
        with:
          myInput: "Shih-Chang"
      - name: output
        run:
          echo ${{ steps.hello.outputs.memory}}
          echo "Total memory successfully output"

